# DROP TABLES

songplay_table_drop = "DROP TABLE IF EXISTS FACT_SONGPLAYS"
user_table_drop = "DROP TABLE IF EXISTS DIM_USERS"
song_table_drop = "DROP TABLE IF EXISTS DIM_SONGS"
artist_table_drop = "DROP TABLE IF EXISTS DIM_ARTISTS"
time_table_drop = "DROP TABLE IF EXISTS DIM_TIME"

# CREATE TABLES

songplay_table_create = ("""
CREATE TABLE IF NOT EXISTS FACT_SONGPLAYS (
SONGPLAY_ID SERIAL PRIMARY KEY,
START_TIME  TIMESTAMP NOT NULL,
USER_ID INT NOT NULL,
LEVEL VARCHAR NOT NULL,
SONG_ID VARCHAR,
ARTIST_ID VARCHAR,
SESSION_ID INT NOT NULL,
LOCATION VARCHAR NOT NULL,
USER_AGENT VARCHAR NOT NULL,
FOREIGN KEY (START_TIME) REFERENCES DIM_TIME (START_TIME),
FOREIGN KEY (USER_ID) REFERENCES DIM_USERS (USER_ID),
FOREIGN KEY (SONG_ID) REFERENCES DIM_SONGS (SONG_ID),
FOREIGN KEY (ARTIST_ID) REFERENCES DIM_ARTISTS (ARTIST_ID));
""")

user_table_create = ("""
CREATE TABLE IF NOT EXISTS DIM_USERS (
USER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL,
GENDER VARCHAR NOT NULL,
LEVEL VARCHAR NOT NULL);
""")

song_table_create = ("""
CREATE TABLE IF NOT EXISTS DIM_SONGS (
SONG_ID VARCHAR PRIMARY KEY,
TITLE VARCHAR NOT NULL,
ARTIST_ID VARCHAR NOT NULL,
YEAR INT NOT NULL,
DURATION FLOAT NOT NULL,
FOREIGN KEY (ARTIST_ID) REFERENCES DIM_ARTISTS (ARTIST_ID));
""")

artist_table_create = ("""
CREATE TABLE IF NOT EXISTS DIM_ARTISTS (
ARTIST_ID VARCHAR PRIMARY KEY,
NAME VARCHAR NOT NULL,
LOCATION VARCHAR NOT NULL,
LATITUDE VARCHAR NOT NULL,
LONGITUDE VARCHAR NOT NULL);
""")

time_table_create = ("""
CREATE TABLE IF NOT EXISTS DIM_TIME (
START_TIME TIMESTAMP PRIMARY KEY,
HOUR INT NOT NULL,
DAY INT NOT NULL,
WEEK INT NOT NULL,
MONTH INT NOT NULL,
YEAR INT NOT NULL,
WEEKDAY VARCHAR NOT NULL);
""")

# INSERT RECORDS

songplay_table_insert = ("""
INSERT INTO FACT_SONGPLAYS(START_TIME,USER_ID,LEVEL,SONG_ID,ARTIST_ID,SESSION_ID,LOCATION,USER_AGENT)
VALUES(%s, %s, %s, %s, %s, %s, %s, %s)
""")

user_table_insert = ("""
INSERT INTO DIM_USERS (USER_ID,FIRST_NAME,LAST_NAME,GENDER,LEVEL)
VALUES(%s, %s, %s, %s, %s)
ON CONFLICT (USER_ID) DO UPDATE SET LEVEL = EXCLUDED.LEVEL
""")

song_table_insert = ("""
INSERT INTO DIM_SONGS (SONG_ID, TITLE, ARTIST_ID, YEAR, DURATION)
VALUES(%s, %s, %s, %s, %s)
ON CONFLICT (SONG_ID) DO NOTHING
""")

artist_table_insert = ("""
INSERT INTO DIM_ARTISTS (ARTIST_ID,NAME,LOCATION,LATITUDE,LONGITUDE)
VALUES(%s, %s, %s, %s, %s)
ON CONFLICT (ARTIST_ID) DO NOTHING
""")


time_table_insert = ("""
INSERT INTO DIM_TIME (START_TIME,HOUR,DAY,WEEK,MONTH,YEAR,WEEKDAY)
VALUES(%s, %s, %s, %s, %s, %s, %s)
ON CONFLICT (START_TIME) DO NOTHING
""")

# FIND SONGS

song_select = ("""
SELECT A.SONG_ID SONG_ID,B.ARTIST_ID ARTIST_ID
FROM DIM_SONGS A
JOIN DIM_ARTISTS B
ON A.ARTIST_ID=B.ARTIST_ID
WHERE A.TITLE = %s AND B.NAME = %s AND A.DURATION = %s
""")

# QUERY LISTS

create_table_queries = [user_table_create, artist_table_create, song_table_create, time_table_create, songplay_table_create]
drop_table_queries = [user_table_drop, artist_table_drop, song_table_drop, time_table_drop, songplay_table_drop]